/**
 * Core data types for a parsed PTCG Live battle log.
 *
 * The Pokémon TCG Live client renders battle logs from an in-memory tree:
 *
 *   BattleLog { Phase[] { MainEntry[] { SubEntry[] } } }
 *
 * When the user exports a log — `BattleLogExporter.ExportBattleLog` in the
 * client's `TPCI.RainierClient` assembly — each node's
 * `PlainTextDisplayString` is written to a StringBuilder, sub-entries prefixed
 * with `"- "` and their optional sub-strings prefixed with `"   • "`.
 *
 * `parseBattleLog` is the mathematical inverse of that exporter. Every
 * `PlainTextDisplayString` is generated by templating exactly one `blog_loc_*`
 * localization key, so this parser reports that `(templateKey, groups)` pair
 * verbatim. It deliberately does not invent a semantic layer on top: a card
 * played is reported as a card played, not as a separately-modelled "play
 * event". Consumers that want semantics build them from the template keys.
 */

/**
 * A single content line, tagged with the localization template it came from
 * and the placeholder values the client filled in.
 *
 * `templateKey` is always a `blog_loc_*` key from the shipped template
 * bundle. `groups` keys are the placeholder names declared by that template
 * (`playerName`, `attackName`, `numDamage`, …). All values are strings — the
 * game does no type conversion at this layer either.
 *
 * `groups` contains only the placeholders that template actually declares, so
 * a narrower template key yields a narrower `groups`. Template matching uses
 * non-greedy captures throughout, so every declared placeholder always
 * participates and no key is ever present with an `undefined` value.
 */
export interface TemplateEvent {
  readonly groups: Readonly<Record<string, string>>;
  /** The exact source line this event was parsed from, prefixes stripped. */
  readonly raw: string;
  /** The `blog_loc_*` key that matched, e.g. `blog_loc_play_to_bench`. */
  readonly templateKey: string;
}

/**
 * A `"- "`-prefixed sub-entry hanging off a main entry, plus its optional
 * `"   • "`-prefixed continuation string.
 *
 * The game's own `IBattleLogSubEntryData.PlainTextSubString` is free-form
 * text, not another templated event — e.g. an enumerated card reveal like
 * `"Ultra Ball, Slowpoke, Kyurem"` — so we preserve it verbatim. Repeated
 * `   • ` lines are joined with `\n`.
 */
export interface SubEntry {
  readonly event: TemplateEvent;
  readonly subString: null | string;
}

/**
 * A top-level line inside a phase, plus any sub-entries the client attached
 * to it (mirrors `IBattleLogMainEntryData.SubEntries`).
 */
export interface MainEntry {
  readonly event: TemplateEvent;
  readonly subEntries: readonly SubEntry[];
}

/**
 * One of the four phase kinds the game defines (`PhaseType.cs`).
 *
 * `Setup` is the pre-turn opening block; `Player` / `Opponent` are turns;
 * `Checkup` is the "Pokémon Checkup" block between turns.
 *
 * `Player` vs `Opponent` is *resolved*, not observed: the game renders both
 * from the same `blog_loc_phase_turn` template and carries no notion of
 * which side is local. The parser decides by comparing the header's
 * `playerName` against the local player's name — see
 * {@link ParseBattleLogOptions.localPlayerName}.
 */
export type PhaseType = "Setup" | "Player" | "Opponent" | "Checkup";

/**
 * A phase block: its header line (rendered from a `blog_loc_phase_*` key)
 * plus the main entries the client attached to it.
 *
 * `displayTurnNumber` mirrors the game's own `(turnNumber + 1) / 2`
 * derivation, counting Player and Opponent turns together as one round. It is
 * `null` for `Setup` and `Checkup`, which have no turn number.
 */
export interface Phase {
  readonly battlePhase: PhaseType;
  readonly displayTurnNumber: null | number;
  readonly mainEntries: readonly MainEntry[];
  /**
   * The player this phase belongs to, resolved from the header at parse time.
   *
   * `null` for `Setup` and `Checkup`, whose headers name no player.
   *
   * This is the value that decides {@link Phase.battlePhase}, captured at the
   * seam where it is known. Consumers should read it here rather than
   * re-matching {@link Phase.plainTextPhaseTitle} against a locale bundle: the
   * title is in the source language, so re-matching it needs a matcher for the
   * right locale, and getting that wrong silently yields no player at all.
   */
  readonly playerName: null | string;
  /** The raw header line, e.g. `"TSLAUJ's Turn"`. */
  readonly plainTextPhaseTitle: string;
}

/**
 * The full parsed log. Root of the AST; the direct inverse of
 * `BattleLogExporter.ExportBattleLog`.
 */
export interface BattleLog {
  readonly phases: readonly Phase[];
}

/**
 * One entry in a template bundle: the localized format string and the
 * placeholder names it declares.
 */
export interface TemplateEntry {
  readonly placeholders: readonly string[];
  /** e.g. `"[playerName] played [cardName] to the Bench."` */
  readonly template: string;
}

/** A locale's full `blog_loc_*` bundle, keyed by template name. */
export type TemplateBundle = Readonly<Record<string, TemplateEntry>>;

/**
 * Every locale PTCG Live ships a battle-log bundle for, in detection-
 * preference order (English first, so an unscoreable log falls back to it).
 *
 * This is the single source of truth for the locale list. `BlogLocale` is
 * derived from it, the matcher registry is built from it, and
 * `scripts/refresh-templates.ts` imports it rather than keeping its own copy.
 * Add a locale here and the type widens with it.
 *
 * `es` (Spain) and `es_la` (Latin America) share most templates and are
 * separated only by body strings.
 */
export const ALL_BLOG_LOCALES = [
  "en",
  "de",
  "es",
  "es_la",
  "fr",
  "it",
  "ptbr",
] as const;

/** Locale codes PTCG Live ships battle-log bundles for. */
export type BlogLocale = (typeof ALL_BLOG_LOCALES)[number];

/** A successful template match: which key matched, and what it captured. */
export interface TemplateMatch {
  readonly groups: Readonly<Record<string, string>>;
  readonly template: string;
  readonly templateKey: string;
}

/**
 * Compiled matcher for one locale's template bundle.
 *
 * `match` returns the first match in specificity order, or `null` if no
 * template matched. Callers that need to know *how many* templates a locale
 * ships can read {@link TemplateMatcher.size}.
 */
export interface TemplateMatcher {
  match(line: string): null | TemplateMatch;
  readonly size: number;
}

/**
 * Which side of the board a summary credit belongs to.
 *
 * `self` is the local player — the one whose name was passed to the parser.
 * `opponent` is everyone else.
 */
export type Credit = "self" | "opponent";

/** Per-side tallies. Keys are {@link Credit} values. */
export type CreditCounts = Readonly<Record<Credit, number>>;

/**
 * Compact summary of a parsed battle log, suitable for rendering a list row
 * without walking every entry.
 *
 * Everything is expressed from the perspective of the local player, so
 * `winner` is `"self"` when they won. A log cut off mid-battle yields
 * `winner: null`.
 */
export interface GameSummary {
  /** Who took the first knockout credit, or `null` if there were none. */
  readonly firstKnockoutBy: null | Credit;
  readonly knockoutsByPlayer: CreditCounts;
  readonly prizesByPlayer: CreditCounts;
  /** Total main + sub entries across every phase. */
  readonly totalEntries: number;
  /** Number of `Player` + `Opponent` phases. */
  readonly turnCount: number;
  readonly winner: null | Credit;
}

/**
 * The full analysis of a single battle-log export: detected locale, resolved
 * player identities, and a compact summary.
 */
export interface BattleLogAnalysis {
  /** The detected locale of the source log. */
  readonly locale: BlogLocale;
  readonly opponentName: null | string;
  readonly playerName: string;
  readonly summary: GameSummary;
}
