/**
 * Core data types for a parsed PTCG Live battle log.
 *
 * The Pokémon TCG Live client renders battle logs from an in-memory tree:
 *
 *   BattleLog { Phase[] { MainEntry[] { SubEntry[] } } }
 *
 * Exporting that tree flattens it to text: each node's display string becomes
 * a line, sub-entries are prefixed with `"- "`, and their optional
 * continuation strings with `"   • "`.
 *
 * `parseBattleLog` is the mathematical inverse of that flattening. Every line
 * is generated by templating exactly one `blog_loc_*` localization key, so
 * this parser reports that `(templateKey, groups)` pair verbatim. It
 * deliberately does not invent a semantic layer on top: a card played is
 * reported as a card played, not as a separately-modelled "play event".
 * Consumers that want semantics build them from the template keys.
 */

/**
 * A single content line, tagged with the localization template it came from
 * and the placeholder values the client filled in.
 *
 * `templateKey` is always a `blog_loc_*` key from the shipped template
 * bundle. `groups` keys are the placeholder names declared by that template
 * (`playerName`, `attackName`, `numDamage`, …). All values are strings — the
 * game does no type conversion at this layer either.
 *
 * `groups` contains only the placeholders that template actually declares, so
 * a narrower template key yields a narrower `groups`. Template matching uses
 * non-greedy captures throughout, so every declared placeholder always
 * participates and no key is ever present with an `undefined` value.
 */
export interface TemplateEvent {
  readonly groups: Readonly<Record<string, string>>;
  /** The exact source line this event was parsed from, prefixes stripped. */
  readonly raw: string;
  /** The `blog_loc_*` key that matched, e.g. `blog_loc_play_to_bench`. */
  readonly templateKey: string;
}

/**
 * A `"- "`-prefixed sub-entry hanging off a main entry, plus its optional
 * `"   • "`-prefixed continuation string.
 *
 * The sub-string is free-form text, not another templated event — e.g. an
 * enumerated card reveal — so we preserve it verbatim. Repeated `   • ` lines
 * are joined with `\n`.
 */
export interface SubEntry {
  readonly event: TemplateEvent;
  readonly subString: null | string;
}

/**
 * A top-level line inside a phase, plus any sub-entries the client attached
 * to it.
 */
export interface MainEntry {
  readonly event: TemplateEvent;
  readonly subEntries: readonly SubEntry[];
}

/**
 * One of the three phase kinds the game defines.
 *
 * `Setup` is the pre-turn opening block; `Turn` is either player's turn;
 * `Checkup` is the "Pokémon Checkup" block between turns. A turn's *side* is a
 * separate axis — see {@link Side}.
 */
export type PhaseKind = "Setup" | "Turn" | "Checkup";

/**
 * Which side of the board something belongs to.
 *
 * `self` is the local player and `opponent` is everyone else. A phase's side
 * and a summary count's side are the same axis, so they share this one type.
 *
 * A side is *resolved*, never observed: the game renders both turns from the
 * same `blog_loc_phase_turn` template and carries no local-player flag. See
 * {@link SideSource} for how the resolution was reached.
 */
export type Side = "self" | "opponent";

/**
 * How a turn's side was resolved.
 *
 * `declared` — the caller passed `playerName`, so the side is a comparison
 * against a name the caller supplied.
 *
 * `inferred` — no name was passed, so the first turn header was taken to be
 * the local player's. That holds when the local player went first, and is
 * wrong when they did not — which is why it is recorded rather than assumed.
 */
export type SideSource = "declared" | "inferred";

/**
 * What every phase carries, whatever its kind.
 *
 * Not exported from the package entry point: consumers narrow {@link Phase} to
 * an arm and read that arm's fields.
 */
export interface PhaseBase {
  readonly mainEntries: readonly MainEntry[];
  /** The raw header line, e.g. `"TSLAUJ's Turn"` or `"Setup"`. */
  readonly plainTextPhaseTitle: string;
}

/** The pre-turn opening block. Names no player, has no turn number. */
export interface SetupPhase extends PhaseBase {
  readonly kind: "Setup";
}

/** The between-turns block. Names no player, has no turn number. */
export interface CheckupPhase extends PhaseBase {
  readonly kind: "Checkup";
}

/**
 * One player's turn.
 *
 * Every field is non-null, because a turn always has a number, a player and a
 * side. That is the point of the union: a `Setup` cannot claim a side and a
 * `Turn` cannot lack one, so neither has to be checked for after the fact.
 */
export interface TurnPhase extends PhaseBase {
  readonly kind: "Turn";
  /**
   * The game's own `(turnNumber + 1) / 2`, counting both sides' turns as one
   * round.
   */
  readonly displayTurnNumber: number;
  /**
   * The player whose turn it is, resolved from the header at parse time.
   *
   * Read it here rather than re-matching
   * {@link PhaseBase.plainTextPhaseTitle} against a locale bundle: the title is
   * in the source language, so re-matching it needs a matcher for the right
   * locale, and getting that wrong silently yields no player at all.
   */
  readonly playerName: string;
  /** Which side this turn belongs to. */
  readonly side: Side;
  /** How {@link TurnPhase.side} was resolved. */
  readonly sideSource: SideSource;
}

/**
 * A phase block: its header line (rendered from a `blog_loc_phase_*` key) plus
 * the main entries the client attached to it.
 *
 * A union rather than one record with nullable side fields. The two non-turn
 * kinds carry neither a side nor a name, and they carry that by *absence*
 * instead of by a `null` every caller has to test.
 */
export type Phase = CheckupPhase | SetupPhase | TurnPhase;

/**
 * The full parsed log. Root of the AST; the direct inverse of
 * `BattleLogExporter.ExportBattleLog`.
 */
export interface BattleLog {
  readonly phases: readonly Phase[];
}

/**
 * One entry in a template bundle: the localized format string and the
 * placeholder names it declares.
 */
export interface TemplateEntry {
  readonly placeholders: readonly string[];
  /** e.g. `"[playerName] played [cardName] to the Bench."` */
  readonly template: string;
}

/** A locale's full `blog_loc_*` bundle, keyed by template name. */
export type TemplateBundle = Readonly<Record<string, TemplateEntry>>;

/**
 * Every locale PTCG Live ships a battle-log bundle for, in detection-
 * preference order (English first, so an unscoreable log falls back to it).
 *
 * This is the single source of truth for the locale list: `BlogLocale` is
 * derived from it and the matcher registry is built from it. Add a locale here
 * and the type widens with it.
 *
 * `es` (Spain) and `es_la` (Latin America) share most templates and are
 * separated only by body strings.
 */
export const ALL_BLOG_LOCALES = [
  "en",
  "de",
  "es",
  "es_la",
  "fr",
  "it",
  "ptbr",
] as const;

/** Locale codes PTCG Live ships battle-log bundles for. */
export type BlogLocale = (typeof ALL_BLOG_LOCALES)[number];

/** A successful template match: which key matched, and what it captured. */
export interface TemplateMatch {
  readonly groups: Readonly<Record<string, string>>;
  readonly template: string;
  readonly templateKey: string;
}

/**
 * Compiled matcher for one locale's template bundle.
 *
 * `match` returns the first match in specificity order, or `null` if no
 * template matched. Callers that need to know *how many* templates a locale
 * ships can read {@link TemplateMatcher.size}.
 */
export interface TemplateMatcher {
  match(line: string): null | TemplateMatch;
  readonly size: number;
}

/** Per-side tallies. Keys are {@link Side} values. */
export type SideCounts = Readonly<Record<Side, number>>;

/**
 * Compact summary of a parsed battle log, suitable for rendering a list row
 * without walking every entry.
 *
 * Everything is expressed from the perspective of the local player, so
 * `winner` is `"self"` when they won. A log cut off mid-battle yields
 * `winner: null`.
 */
export interface GameSummary {
  /** Who took the first knockout credit, or `null` if there were none. */
  readonly firstKnockoutBy: null | Side;
  readonly knockoutsByPlayer: SideCounts;
  readonly prizesByPlayer: SideCounts;
  /** Total main + sub entries across every phase. */
  readonly totalEntries: number;
  /** Number of `Turn` phases. */
  readonly turnCount: number;
  readonly winner: null | Side;
}

/**
 * The full analysis of a single battle-log export: detected locale, resolved
 * player identities, and a compact summary.
 */
export interface BattleLogAnalysis {
  /** The detected locale of the source log. */
  readonly locale: BlogLocale;
  readonly opponentName: null | string;
  readonly playerName: string;
  readonly summary: GameSummary;
}
